### ISSUE TITLE
火狐浏览器直播间增强不显示了

### ISSUE THREAD

**Issue by kevinluo6188** [indefined/UserScript-for-Bilibili#1]
在直播间不显示了

未知原因，重启电脑正常，无果

**Comment by indefined** [comment]
请说明具体浏览器、脚本管理器，是偶然还是必然现象。本脚本并没有做全兼容，如果不在说明里面的兼容列表的话可能会出现不支持，而且现在的逻辑是可能出现偶尔不显示的，如果刷新能正常工作的话就先用着吧等下次更新或许会把启动检测做了

**Comment by kevinluo6188** [comment]
火狐60.0.1 64位
油猴子 v4.6.5757

[flv.js] > Loader error, code = -1, msg = ProgressEvent error
decorator.min.js:487:165288
[flv.js] > IOException: type = Exception, code = -1, msg = ProgressEvent error
decorator.min.js:487:165288
Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2018 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
app.9f35862f26b88c0b143d.js:1:663437
Version: V4.0.0 "Life Experience", CodeName: Neptune.
app.9f35862f26b88c0b143d.js:1:663597
XML 解析错误：格式不佳
位置：
行 1，列 75：
[Error] 直播心跳请求错误: undefined - undefined
vendor.17faccc0b432e7cc172f.js:46:3622
[Error] HeartBeat 请求失败:  
Object { code: 65531, msg: "", message: "", data: {} }
app.9f35862f26b88c0b143d.js:1:224933
[Player] Tracking Mi (0).
decorator.min.js:424:445
[flv.js] > Playback seems stuck at 0, seek to 0.067
decorator.min.js:487:165726
源映射错误：request failed with status 404
源 URL：https://static.hdslb.com/live-static/libs/jquery/jquery-1.11.3.min.js
源映射 URL：jquery.min.map[详细了解]
[Player] Tracking Wn (344).
decorator.min.js:424:445
[Error] 直播心跳请求错误: undefined - undefined
vendor.17faccc0b432e7cc172f.js:46:3622
[Player] Tracking Wn (344).
decorator.min.js:424:445

**Comment by indefined** [comment]
火狐这边没有做过兼容测试，我这边使用chrome偶尔会出现页面加载延迟导致脚本不执行情况，控制台log里面没有跟本脚本相关的错误信息可能是这种原因，刚刚的提交 [349b34b](https://github.com/indefined/UserScript-for-Bilibili/commit/349b34b824a9c608eb7f26e39c2a80e7a5cb1d21) 尝试修复了这个问题，你可以更新试试

**Comment by kevinluo6188** [comment]
劳烦在greasyfork修改下~

**Comment by indefined** [comment]
greasyfork使用webhook和github同步更新

**Comment by kevinluo6188** [comment]
然而我并没有看到greasyfork更新~

**Comment by kevinluo6188** [comment]
还是不显示- -

**Comment by indefined** [comment]
我这边使用火狐相同环境测试了没有问题，是一开始就不能用还是以前能用现在没有了？尝试观察网页地址是否匹配、Tampermonkey图标上脚本是否启动等更多有用信息，如果没有更多异常情况的话这边也无法做适配

**Comment by kevinluo6188** [comment]
网址匹配 图标已经启动 一开始就不用

**Comment by indefined** [comment]
这边没有足够的信息复现问题做兼容，我会继续观察问题的，如果有更多信息欢迎继续反馈

**Comment by kevinluo6188** [comment]
需要信息可以说明 我可以尝试提供

**Comment by kevinluo6188** [comment]
可能是因为我勋章25个？

**Comment by indefined** [comment]
不应该是勋章的原因，勋章和头衔的数量都做过考虑处理的，这个脚本还是算比较简单的，执行过程中的异常基本都进行了捕捉和输出，如果出问题的话比较大可能是在查找页面元素的时候找不到对象，但如果是被执行元素对象不存在控制台也应该会输出异常错误信息，现在控制台没有消息就无从下手了。我也查看了火狐渲染的页面元素需要操作到的对象都有，我这边也执行正常。现在没有头绪问题的出错点在哪里所以也不知道需要的具体信息

**Comment by kevinluo6188** [comment]
![default](https://user-images.githubusercontent.com/36571233/41097937-5abee8cc-6a8c-11e8-980d-21c866b3c353.png)
emmmm好了 目测是这样

**Comment by kevinluo6188** [comment]
emmmm节奏风暴为什么没有选择的提示(选择语句

**Comment by kevinluo6188** [comment]
emmmmm我并没有解决方案 只是重新启动了电脑
