### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by youth1996** [indefined/UserScript-for-Bilibili#2]
既然现在新活动道具包的图标使用了亿元的图片，那就可以把背包的图片换为辣条的（反正辣条真的已经进背包了，背包都是辣条），这样也可以避免在某些抽奖直播间加载不出来背包。

**Comment by youth1996** [comment]
还有就是，现在有两个游戏机在道具背包

**Comment by indefined** [comment]
好建议，这个可以做。
至于其它礼物里的两个游戏机，因为接口就是返回了两个游戏机，虽然看上去都是一样的参数也大都相同，但是id是不一样的，一个是旧的id一个是新的，原则上应该都能送，但是这个礼物是是限区的，手游区外面礼物栏就有的，不在手游区也送不出去。这个接口挺神经病的，现在是返回什么就显示什么，基本就是用来看的，如果要一个个过滤的话太多不可靠因素了
